services:
  postgres:
    image: postgres:16
    container_name: postgres-autoflex
    environment:
      POSTGRES_DB: autoflexdb
      POSTGRES_USER: autoflex
      POSTGRES_PASSWORD: autoflex
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
